server:
  port: 8900

dependencies:
  datacatalog: "${datacatalog.uri:http://localhost:5000}"
  user-management: "${user.management.uri:http://localhost:9998}"

security:
  ignored: /open,/sdoc.jsp,/*.js,/api-docs,/api-docs/default/*,/images/*,/lib/*,/css/*,/v2/api-docs

spring.oauth2.resource:
    id: tap
    jwt:
      keyUri: ${sso.tokenKey}

logging:
  level:
    org.springframework.security: DEBUG
    org.trustedanalytics: DEBUG

cf:
  resource: ${sso.apiEndpoint}
  uaa: ${sso.uaaUri}

endpoints.enabled: false
endpoints.health.enabled: true

hdfs:
  configDir: /etc/hadoop/
  uri: "hdfs://nameservice1/tmp/%{organization}/brokers/userspace/efeedfce-05f5-4600-95f8-efd1f6c480f4/"
kerberos:
  kdc: kdc.host.addr
  realm: KDC_REALM_NAME
  user: cf
  pass: haselko