server:
  port: 8900

dependencies:
  datacatalog: "${vcap.services.datacatalog.credentials.host:http://localhost:5000}"
  user-management: "${user.management.host:http://localhost:9998}"

security:
  ignored: /open,/sdoc.jsp,/*.js,/api-docs,/api-docs/default/*,/images/*,/lib/*,/css/*,/v2/api-docs

spring.oauth2.resource:
    id: cloud_controller
    jwt:
      keyUri: ${vcap.services.sso.credentials.tokenKey}

logging:
  level:
    org.springframework.security: DEBUG
    org.trustedanalytics: DEBUG

cf:
  resource: ${vcap.services.sso.credentials.apiEndpoint}
  uaa: ${vcap.services.sso.credentials.uaaUri}

endpoints.enabled: false
endpoints.health.enabled: true
