server:
  port: 8900

dependencies:
  datacatalog: "${datacatalog.uri:http://localhost:5000}"
  user-management: "${user.management.uri:http://localhost:9998}"

security:
  ignored: /open,/sdoc.jsp,/*.js,/api-docs,/api-docs/default/*,/images/*,/lib/*,/css/*,/v2/api-docs,/health,/info

spring.oauth2.resource:
    id: tap
    jwt:
      keyUri: ${sso.tokenKey}

logging:
  level:
    org.springframework.security: DEBUG
    org.trustedanalytics: DEBUG

cf:
  resource: ${sso.apiEndpoint}
  uaa: ${sso.uaaUri}

endpoints.enabled: false
endpoints.health.enabled: true
endpoints.info.enabled: true
endpoints.info.sensitive: false

hdfs:
  configDir: /etc/hadoop/
  uri: "hdfs://nameservice1/tmp/%{organization}/brokers/userspace/efeedfce-05f5-4600-95f8-efd1f6c480f4/"
kerberos:
  kdc: kdc.host.addr
  realm: KDC_REALM_NAME
  user: cf
  pass: haselko

# http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-application-info-git
management:
  info:
    git:
      mode: full

# http://docs.spring.io/spring-boot/docs/current/reference/html/howto-build.html#howto-build-info
info:
  name: "@project.artifactId@"
  app_version: "@project.version@"
  build:
    group: "@project.groupId@"
    artifact: "@project.artifactId@"
    version: "@project.version@"
    name: "@project.name@"
    time: "@build.time@"
